/* $Id: locators.h 70835 2018-01-31 14:49:25Z vboxsync $ */
/** @file
 * Placeholder "locators.h" that wsmousevar.h needs (bad hygiene).
 *
 * It's normally generated by config(8), but see the explanatory
 * comment in vboxguest.ioconf
 */
#define WSMOUSEDEVCF_MUX 0
